services:
  boot-1:
    image: wakuorg/nwaku:v0.38.1
    ports:
      - "60001:60001"
      - "8645:8645"
      - "49000:49000/udp"
    entrypoint: [
      "/usr/bin/wakunode",
      "--discv5-discovery=true",
      "--discv5-enr-auto-update=True",
      "--discv5-udp-port=49000",
      "--cluster-id=16",
      "--num-shards-in-network=0",
      "--dns-addrs-name-server=127.0.0.11",
      "--filter=true",
      "--lightpush=true",
      "--log-level=INFO",
      "--max-connections=18000",
      "--max-msg-size=1024KiB",
      "--ip-colocation-limit=100",
      "--nodekey=697b008f979c8ae38c1e4e0b9bc3712dd39e2355f49eaf6c63d92f7edd13704d",
      "--peer-exchange=true",
      "--relay=true",
      "--rest=true",
      "--rest-address=0.0.0.0",
      "--rest-admin",
      "--rest-port=8645",
      "--shard=1",
      "--shard=32",
      "--shard=64",
      "--shard=128",
      "--shard=256",
      "--staticnode=/dns4/store/tcp/60002/p2p/16Uiu2HAm4y9o3GARfphq8jN1wsVhezCHPMmRuekHCCKJ1EsgzVBi",
      "--storenode=/dns4/store/tcp/60002/p2p/16Uiu2HAm4y9o3GARfphq8jN1wsVhezCHPMmRuekHCCKJ1EsgzVBi",
      "--tcp-port=60001",
      "--nat=extip:127.0.0.1",
    ]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8645/debug/v1/info || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  store:
    image: wakuorg/nwaku:v0.38.1
    ports:
      - "60002:60002"
      - "8646:8646"
      - "49001:49001/udp"
    entrypoint: [
      "/usr/bin/wakunode",
      "--discv5-discovery=true",
      "--discv5-enr-auto-update=True",
      "--discv5-udp-port=49001",
      "--cluster-id=16",
      "--num-shards-in-network=0",
      "--dns-addrs-name-server=127.0.0.11",
      "--log-level=INFO",
      "--max-connections=18000",
      "--max-msg-size=1024KiB",
      "--ip-colocation-limit=100",
      "--nodekey=ba4e531d4ef543fabd838ef4e731d35dfa4deceea8f4a5992ad7f29764c70035",
      "--peer-exchange=false",
      "--relay=true",
      "--rest=true",
      "--rest-address=0.0.0.0",
      "--rest-admin",
      "--rest-port=8646",
      "--shard=1",
      "--shard=32",
      "--shard=64",
      "--shard=128",
      "--shard=256",
      "--staticnode=/dns4/boot-1/tcp/60001/p2p/16Uiu2HAmMgYeJrjruJGCgL96aaP2nf85PGsRVkXLyhG2joJMH4pH",
      "--store=true",
      "--store-message-db-url=sqlite:///tmp/store1.db",
      "--store-message-retention-policy=time:86400",
      "--tcp-port=60002",
      "--nat=extip:127.0.0.1",
    ]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8646/debug/v1/info || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  store-2:
    image: wakuorg/nwaku:v0.38.1
    ports:
      - "60003:60003"
      - "8647:8647"
      - "49002:49002/udp"
    entrypoint: [
      "/usr/bin/wakunode",
      "--discv5-discovery=true",
      "--discv5-enr-auto-update=True",
      "--discv5-udp-port=49002",
      "--cluster-id=16",
      "--num-shards-in-network=0",
      "--dns-addrs-name-server=127.0.0.11",
      "--log-level=INFO",
      "--max-connections=18000",
      "--max-msg-size=1024KiB",
      "--ip-colocation-limit=100",
      "--nodekey=c2a4e44652cd44b2b73093e7d2dba0a1e841e24e59db4a3a8c8e660e6e4d1b3a",
      "--peer-exchange=false",
      "--relay=true",
      "--rest=true",
      "--rest-address=0.0.0.0",
      "--rest-admin",
      "--rest-port=8647",
      "--shard=1",
      "--shard=32",
      "--shard=64",
      "--shard=128",
      "--shard=256",
      "--staticnode=/dns4/boot-1/tcp/60001/p2p/16Uiu2HAmMgYeJrjruJGCgL96aaP2nf85PGsRVkXLyhG2joJMH4pH",
      "--store=true",
      "--store-message-db-url=sqlite:///tmp/store2.db",
      "--store-message-retention-policy=time:86400",
      "--tcp-port=60003",
      "--nat=extip:127.0.0.1",
    ]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8647/debug/v1/info || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10