## Pausable-services mobile API (PausableServices/PauseServices/ResumeServices).
## These are libstatus C exports generated by status-go's
## tools/generate-cbindings from the public functions in mobile/status.go. The
## statusgo package's wrapper does not bind them yet, so they are declared here
## with the same importc pattern.

import json, chronicles

logScope:
  topics = "rpc-pausable-services"

proc statusGoPausableServices(): cstring {.importc: "PausableServices".}
proc statusGoPauseServices(namesJson: cstring): cstring {.importc: "PauseServices".}
proc statusGoResumeServices(namesJson: cstring): cstring {.importc: "ResumeServices".}

proc parsePausableServiceNames*(response: string): seq[string] =
  ## Service names out of PausableServices()' response — a JSON array of
  ## {name, state} objects. Empty for anything else: "null" when the node is
  ## not running, error objects, malformed JSON (mirrors the Android service's
  ## fetchPausableServiceNames guard).
  if response.len == 0:
    return @[]
  try:
    let parsed = parseJson(response)
    if parsed.kind != JArray:
      return @[]
    for item in parsed.getElems():
      let name = item{"name"}.getStr()
      if name.len > 0:
        result.add(name)
  except CatchableError:
    result = @[]

proc apiResponseError*(response: string): string =
  ## The error field of a mobile-API {"error": ...} response; "" for success
  ## or an unparsable response.
  try:
    result = parseJson(response){"error"}.getStr()
  except CatchableError:
    result = ""

proc pausableServiceNames*(): seq[string] =
  ## Names of all pausable services currently registered in status-go;
  ## empty when the node is not running.
  parsePausableServiceNames($statusGoPausableServices())

proc pauseServices*(names: seq[string]) =
  let err = apiResponseError($statusGoPauseServices(cstring($(%names))))
  if err.len > 0:
    warn "PauseServices returned an error", err

proc resumeServices*(names: seq[string]) =
  let err = apiResponseError($statusGoResumeServices(cstring($(%names))))
  if err.len > 0:
    warn "ResumeServices returned an error", err
