DEFAULT_PIN = '111111'
DEFAULT_PUK = '000000000000'
NEW_PIN = '654321'
WRONG_PIN = '000000'

KEYCARD_EMPTY_TITLE = 'Keycard is empty'
KEYCARD_PROFILE_DETAILS_TITLE = 'Keycard stores Status profile key pair'
KEYCARD_STORES_KEY_PAIR_TITLE = 'Keycard stores key pair'
KEYCARD_BLOCKED_TITLE = 'Keycard is blocked'
KEYCARD_BLOCKED_PIN_MESSAGE = 'Keycard is blocked due to three failed PIN input attempts'
KEYCARD_RESET_SUCCESS_TITLE = 'Keycard has been reset'
KEYCARD_UNBLOCK_SUCCESS_TITLE = 'Keycard has been unblocked'
KEYCARD_SET_PUK_SUCCESS_TITLE = 'Keycard\u2019s PUK successfully set'
KEYCARD_PROFILE_ALREADY_EXISTS_TITLE = 'Profile already exists'
KEYCARD_ON_KEYCARD_LABEL = 'On Keycard'
