// Captured from the ObjectProxyModel-based HomePageAdaptor (before #22640); characterization data.
.pragma library

var dump = false

var defaultEntries = [
    {"key": "4;12", "id": "12", "sectionType": 4, "name": "About", "icon": "info", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;11", "id": "11", "sectionType": 4, "name": "Advanced", "icon": "settings-advanced", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;6", "id": "6", "sectionType": 4, "name": "Appearance", "icon": "appearance", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;101", "id": "101", "sectionType": 4, "name": "Back up recovery phrase", "icon": "seed-phrase", "color": "#4360df", "banner": null, "hasNotification": true, "notificationsCount": 1, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;10", "id": "10", "sectionType": 4, "name": "Browser", "icon": "browser", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": true, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "2;id3", "id": "id3", "sectionType": 2, "name": "Channel Y_1", "icon": "💩", "color": "#51d0f0", "banner": null, "hasNotification": true, "notificationsCount": 0, "enabled": null, "chatType": 6, "onlineStatus": 0, "lastMessageText": "len344:523fb4cf", "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "2;id4", "id": "id4", "sectionType": 2, "name": "Channel Y_2", "icon": "", "color": "#ff0000", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": 0, "onlineStatus": 0, "lastMessageText": "bold break line italic", "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "2;id5", "id": "id5", "sectionType": 2, "name": "Channel Y_3", "icon": "https://assets.coingecko.com/coins/images/17139/standard/10631.png", "color": "#fa6565", "banner": null, "hasNotification": true, "notificationsCount": 1, "enabled": null, "chatType": 3, "onlineStatus": 0, "lastMessageText": "💩", "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "3;id102", "id": "id102", "sectionType": 3, "name": "Coinbase", "icon": "len2198:ab938bda", "color": "#808000", "banner": "len13022:5ec405f3", "hasNotification": false, "notificationsCount": 0, "enabled": true, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": 40, "activeMembers": 20, "pending": true, "banned": false, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;13", "id": "13", "sectionType": 4, "name": "Communities", "icon": "communities", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;2", "id": "2", "sectionType": 4, "name": "Contacts", "icon": "contact", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "3;id106", "id": "id106", "sectionType": 3, "name": "Dribble", "icon": "len2866:f87e1372", "color": "#ffa500", "banner": "", "hasNotification": true, "notificationsCount": 100, "enabled": true, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": 3, "activeMembers": 0, "pending": false, "banned": false, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;3", "id": "3", "sectionType": 4, "name": "ENS usernames", "icon": "username", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": true, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "1;0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8884", "id": "0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8884", "sectionType": 1, "name": "Fab (key)", "icon": "🔑", "color": "#c78f67", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": "key", "currencyBalance": "999.00 USD", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "1;0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8882", "id": "0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8882", "sectionType": 1, "name": "Family (seed)", "icon": "🎨", "color": "#ec266c", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": "seed", "currencyBalance": "110.05 USD", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "1;0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8881", "id": "0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8881", "sectionType": 1, "name": "Hot wallet (generated)", "icon": "☀️", "color": "#216266", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": "generated", "currencyBalance": "10.00 USD", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "3;id107", "id": "id107", "sectionType": 3, "name": "Just Text", "icon": "", "color": "#dc143c", "banner": "", "hasNotification": false, "notificationsCount": 0, "enabled": true, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": 1, "activeMembers": 0, "pending": false, "banned": false, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;14", "id": "14", "sectionType": 4, "name": "Keycard", "icon": "keycard", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;7", "id": "7", "sectionType": 4, "name": "Language & Currency", "icon": "language", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;4", "id": "4", "sectionType": 4, "name": "Messaging", "icon": "chat", "color": "#4360df", "banner": null, "hasNotification": true, "notificationsCount": 4, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;8", "id": "8", "sectionType": 4, "name": "Notifications", "icon": "notification", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;18", "id": "18", "sectionType": 4, "name": "On-device backup", "icon": "download", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;19", "id": "19", "sectionType": 4, "name": "P2P network", "icon": "p2p", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;1", "id": "1", "sectionType": 4, "name": "Password", "icon": "password", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;17", "id": "17", "sectionType": 4, "name": "Privacy and security", "icon": "security", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;0", "id": "0", "sectionType": 4, "name": "Profile", "icon": "profile", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "2;id1", "id": "id1", "sectionType": 2, "name": "Punxnotdead", "icon": "len1150:112d27ba", "color": "#887af9", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": 1, "onlineStatus": 1, "lastMessageText": "https://status.app/c/iwuAChYKBGZld2YSA2ZldxgCIgcjODhCMEZGAw==#zQ3shk6ceLwoMYCZnV29hwkRfRMEiw6nFrpViCoLucaycPu9y", "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "3;id104", "id": "id104", "sectionType": 3, "name": "Rarible", "icon": "len1638:2c62be3d", "color": "#ffc0cb", "banner": "", "hasNotification": false, "notificationsCount": 33, "enabled": true, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": 1, "activeMembers": 1, "pending": false, "banned": true, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;100", "id": "100", "sectionType": 4, "name": "Sign out & Quit", "icon": "logout", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "3;id103", "id": "id103", "sectionType": 3, "name": "Socks", "icon": "len3014:4241c9ab", "color": "#ffff00", "banner": "len28258:77ee79d7", "hasNotification": false, "notificationsCount": 33, "enabled": true, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": 42, "activeMembers": 20, "pending": false, "banned": false, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "3;id105", "id": "id105", "sectionType": 3, "name": "Spotify", "icon": "len4730:923d51bc", "color": "#008000", "banner": "", "hasNotification": true, "notificationsCount": 0, "enabled": true, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": 10000, "activeMembers": 200, "pending": false, "banned": false, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "3;id100", "id": "id100", "sectionType": 3, "name": "Status.app", "icon": "len1530:f11d2e52", "color": "#0000cd", "banner": "len38675:2a8ee1d2", "hasNotification": true, "notificationsCount": 3, "enabled": true, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": 82, "activeMembers": 61, "pending": false, "banned": false, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "3;id101", "id": "id101", "sectionType": 3, "name": "SuperRare", "icon": "len1938:388c0bc3", "color": "#708090", "banner": "len61050:5230a0ab", "hasNotification": true, "notificationsCount": 0, "enabled": true, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": 10, "activeMembers": 4, "pending": false, "banned": false, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;9", "id": "9", "sectionType": 4, "name": "Syncing", "icon": "rotate", "color": "#4360df", "banner": null, "hasNotification": true, "notificationsCount": 2, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": true, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "1;0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8883", "id": "0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8883", "sectionType": 1, "name": "Tag Heuer (watch)", "icon": "⌚", "color": "#cb6256", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": "watch", "currencyBalance": "3.00 USD", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "999;https://dapp.test/2", "id": "https://dapp.test/2", "sectionType": 999, "name": "Test dApp 2", "icon": "dapp", "color": "#4360df", "banner": null, "hasNotification": null, "notificationsCount": null, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": "https://raw.githubusercontent.com/WalletConnect/walletconnect-assets/refs/heads/master/Icon/Blue (Default)/Icon.svg", "pinned": false, "timestamp": 0},
    {"key": "999;https://dapp.test/4", "id": "https://dapp.test/4", "sectionType": 999, "name": "Test dApp 4 - very long name !!!!!!!!!!!!!!!!", "icon": "https://react-app.walletconnect.com/assets/eip155-10.png", "color": "#4360df", "banner": null, "hasNotification": null, "notificationsCount": null, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": "https://raw.githubusercontent.com/WalletConnect/walletconnect-assets/refs/heads/master/Icon/Blue (Default)/Icon.svg", "pinned": false, "timestamp": 0},
    {"key": "999;https://dapp.test/very_long/url/unusual", "id": "https://dapp.test/very_long/url/unusual", "sectionType": 999, "name": "Test dApp 5 - very long url", "icon": "https://react-app.walletconnect.com/assets/eip155-1.png", "color": "#4360df", "banner": null, "hasNotification": null, "notificationsCount": null, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": "", "pinned": false, "timestamp": 0},
    {"key": "4;5", "id": "5", "sectionType": 4, "name": "Wallet", "icon": "wallet", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "999;https://dapp.test/3", "id": "https://dapp.test/3", "sectionType": 999, "name": "dapp.test", "icon": "dapp", "color": "#4360df", "banner": null, "hasNotification": null, "notificationsCount": null, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": "", "pinned": false, "timestamp": 0},
    {"key": "1;0x7F47C2e18a4BBf5487E6fb082eC2D9Ab0E6d7240", "id": "0x7F47C2e18a4BBf5487E6fb082eC2D9Ab0E6d7240", "sectionType": 1, "name": "helloworld", "icon": "😋", "color": "#2a4af5", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": "", "currencyBalance": "1.25 USD", "connectorBadge": null, "pinned": false, "timestamp": 0}
]

var interactionEntries = [
    {"key": "1;0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8884", "id": "0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8884", "sectionType": 1, "name": "Fab (key)", "icon": "🔑", "color": "#c78f67", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": "key", "currencyBalance": "999.00 USD", "connectorBadge": null, "pinned": false, "timestamp": 3000},
    {"key": "3;id106", "id": "id106", "sectionType": 3, "name": "Dribble", "icon": "len2866:f87e1372", "color": "#ffa500", "banner": "", "hasNotification": true, "notificationsCount": 100, "enabled": true, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": 3, "activeMembers": 0, "pending": false, "banned": false, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": true, "timestamp": 2000},
    {"key": "2;id1", "id": "id1", "sectionType": 2, "name": "Punxnotdead", "icon": "len1150:112d27ba", "color": "#887af9", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": 1, "onlineStatus": 1, "lastMessageText": "https://status.app/c/iwuAChYKBGZld2YSA2ZldxgCIgcjODhCMEZGAw==#zQ3shk6ceLwoMYCZnV29hwkRfRMEiw6nFrpViCoLucaycPu9y", "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": true, "timestamp": 1000},
    {"key": "4;1", "id": "1", "sectionType": 4, "name": "Password", "icon": "password", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 500},
    {"key": "4;12", "id": "12", "sectionType": 4, "name": "About", "icon": "info", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;11", "id": "11", "sectionType": 4, "name": "Advanced", "icon": "settings-advanced", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;6", "id": "6", "sectionType": 4, "name": "Appearance", "icon": "appearance", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;101", "id": "101", "sectionType": 4, "name": "Back up recovery phrase", "icon": "seed-phrase", "color": "#4360df", "banner": null, "hasNotification": true, "notificationsCount": 1, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;10", "id": "10", "sectionType": 4, "name": "Browser", "icon": "browser", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": true, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "2;id3", "id": "id3", "sectionType": 2, "name": "Channel Y_1", "icon": "💩", "color": "#51d0f0", "banner": null, "hasNotification": true, "notificationsCount": 0, "enabled": null, "chatType": 6, "onlineStatus": 0, "lastMessageText": "len344:523fb4cf", "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "2;id4", "id": "id4", "sectionType": 2, "name": "Channel Y_2", "icon": "", "color": "#ff0000", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": 0, "onlineStatus": 0, "lastMessageText": "bold break line italic", "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "2;id5", "id": "id5", "sectionType": 2, "name": "Channel Y_3", "icon": "https://assets.coingecko.com/coins/images/17139/standard/10631.png", "color": "#fa6565", "banner": null, "hasNotification": true, "notificationsCount": 1, "enabled": null, "chatType": 3, "onlineStatus": 0, "lastMessageText": "💩", "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "3;id102", "id": "id102", "sectionType": 3, "name": "Coinbase", "icon": "len2198:ab938bda", "color": "#808000", "banner": "len13022:5ec405f3", "hasNotification": false, "notificationsCount": 0, "enabled": true, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": 40, "activeMembers": 20, "pending": true, "banned": false, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;13", "id": "13", "sectionType": 4, "name": "Communities", "icon": "communities", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;2", "id": "2", "sectionType": 4, "name": "Contacts", "icon": "contact", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;3", "id": "3", "sectionType": 4, "name": "ENS usernames", "icon": "username", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": true, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "1;0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8882", "id": "0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8882", "sectionType": 1, "name": "Family (seed)", "icon": "🎨", "color": "#ec266c", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": "seed", "currencyBalance": "110.05 USD", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "1;0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8881", "id": "0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8881", "sectionType": 1, "name": "Hot wallet (generated)", "icon": "☀️", "color": "#216266", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": "generated", "currencyBalance": "10.00 USD", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "3;id107", "id": "id107", "sectionType": 3, "name": "Just Text", "icon": "", "color": "#dc143c", "banner": "", "hasNotification": false, "notificationsCount": 0, "enabled": true, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": 1, "activeMembers": 0, "pending": false, "banned": false, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;14", "id": "14", "sectionType": 4, "name": "Keycard", "icon": "keycard", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;7", "id": "7", "sectionType": 4, "name": "Language & Currency", "icon": "language", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;4", "id": "4", "sectionType": 4, "name": "Messaging", "icon": "chat", "color": "#4360df", "banner": null, "hasNotification": true, "notificationsCount": 4, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;8", "id": "8", "sectionType": 4, "name": "Notifications", "icon": "notification", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;18", "id": "18", "sectionType": 4, "name": "On-device backup", "icon": "download", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;19", "id": "19", "sectionType": 4, "name": "P2P network", "icon": "p2p", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;17", "id": "17", "sectionType": 4, "name": "Privacy and security", "icon": "security", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;0", "id": "0", "sectionType": 4, "name": "Profile", "icon": "profile", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "3;id104", "id": "id104", "sectionType": 3, "name": "Rarible", "icon": "len1638:2c62be3d", "color": "#ffc0cb", "banner": "", "hasNotification": false, "notificationsCount": 33, "enabled": true, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": 1, "activeMembers": 1, "pending": false, "banned": true, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;100", "id": "100", "sectionType": 4, "name": "Sign out & Quit", "icon": "logout", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "3;id103", "id": "id103", "sectionType": 3, "name": "Socks", "icon": "len3014:4241c9ab", "color": "#ffff00", "banner": "len28258:77ee79d7", "hasNotification": false, "notificationsCount": 33, "enabled": true, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": 42, "activeMembers": 20, "pending": false, "banned": false, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "3;id105", "id": "id105", "sectionType": 3, "name": "Spotify", "icon": "len4730:923d51bc", "color": "#008000", "banner": "", "hasNotification": true, "notificationsCount": 0, "enabled": true, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": 10000, "activeMembers": 200, "pending": false, "banned": false, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "3;id100", "id": "id100", "sectionType": 3, "name": "Status.app", "icon": "len1530:f11d2e52", "color": "#0000cd", "banner": "len38675:2a8ee1d2", "hasNotification": true, "notificationsCount": 3, "enabled": true, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": 82, "activeMembers": 61, "pending": false, "banned": false, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "3;id101", "id": "id101", "sectionType": 3, "name": "SuperRare", "icon": "len1938:388c0bc3", "color": "#708090", "banner": "len61050:5230a0ab", "hasNotification": true, "notificationsCount": 0, "enabled": true, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": 10, "activeMembers": 4, "pending": false, "banned": false, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "4;9", "id": "9", "sectionType": 4, "name": "Syncing", "icon": "rotate", "color": "#4360df", "banner": null, "hasNotification": true, "notificationsCount": 2, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": true, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "1;0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8883", "id": "0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8883", "sectionType": 1, "name": "Tag Heuer (watch)", "icon": "⌚", "color": "#cb6256", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": "watch", "currencyBalance": "3.00 USD", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "999;https://dapp.test/2", "id": "https://dapp.test/2", "sectionType": 999, "name": "Test dApp 2", "icon": "dapp", "color": "#4360df", "banner": null, "hasNotification": null, "notificationsCount": null, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": "https://raw.githubusercontent.com/WalletConnect/walletconnect-assets/refs/heads/master/Icon/Blue (Default)/Icon.svg", "pinned": false, "timestamp": 0},
    {"key": "999;https://dapp.test/4", "id": "https://dapp.test/4", "sectionType": 999, "name": "Test dApp 4 - very long name !!!!!!!!!!!!!!!!", "icon": "https://react-app.walletconnect.com/assets/eip155-10.png", "color": "#4360df", "banner": null, "hasNotification": null, "notificationsCount": null, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": "https://raw.githubusercontent.com/WalletConnect/walletconnect-assets/refs/heads/master/Icon/Blue (Default)/Icon.svg", "pinned": false, "timestamp": 0},
    {"key": "999;https://dapp.test/very_long/url/unusual", "id": "https://dapp.test/very_long/url/unusual", "sectionType": 999, "name": "Test dApp 5 - very long url", "icon": "https://react-app.walletconnect.com/assets/eip155-1.png", "color": "#4360df", "banner": null, "hasNotification": null, "notificationsCount": null, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": "", "pinned": false, "timestamp": 0},
    {"key": "4;5", "id": "5", "sectionType": 4, "name": "Wallet", "icon": "wallet", "color": "#4360df", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": false, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": false, "timestamp": 0},
    {"key": "999;https://dapp.test/3", "id": "https://dapp.test/3", "sectionType": 999, "name": "dapp.test", "icon": "dapp", "color": "#4360df", "banner": null, "hasNotification": null, "notificationsCount": null, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": "", "pinned": false, "timestamp": 0},
    {"key": "1;0x7F47C2e18a4BBf5487E6fb082eC2D9Ab0E6d7240", "id": "0x7F47C2e18a4BBf5487E6fb082eC2D9Ab0E6d7240", "sectionType": 1, "name": "helloworld", "icon": "😋", "color": "#2a4af5", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": "", "currencyBalance": "1.25 USD", "connectorBadge": null, "pinned": false, "timestamp": 0}
]

var interactionPinned = [
    {"key": "2;id1", "id": "id1", "sectionType": 2, "name": "Punxnotdead", "icon": "len1150:112d27ba", "color": "#887af9", "banner": null, "hasNotification": false, "notificationsCount": 0, "enabled": null, "chatType": 1, "onlineStatus": 1, "lastMessageText": "https://status.app/c/iwuAChYKBGZld2YSA2ZldxgCIgcjODhCMEZGAw==#zQ3shk6ceLwoMYCZnV29hwkRfRMEiw6nFrpViCoLucaycPu9y", "sectionName": null, "members": null, "activeMembers": null, "pending": false, "banned": null, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": true, "timestamp": 1000},
    {"key": "3;id106", "id": "id106", "sectionType": 3, "name": "Dribble", "icon": "len2866:f87e1372", "color": "#ffa500", "banner": "", "hasNotification": true, "notificationsCount": 100, "enabled": true, "chatType": null, "onlineStatus": null, "lastMessageText": null, "sectionName": null, "members": 3, "activeMembers": 0, "pending": false, "banned": false, "isExperimental": null, "walletType": null, "currencyBalance": "", "connectorBadge": null, "pinned": true, "timestamp": 2000}
]

var search_a = ["4;12", "4;11", "4;6", "4;101", "2;id3", "2;id4", "2;id5", "3;id102", "4;2", "4;3", "1;0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8884", "1;0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8882", "1;0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8881", "4;14", "4;7", "4;4", "4;8", "4;18", "4;1", "4;17", "2;id1", "3;id104", "3;id100", "3;id101", "1;0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8883", "999;https://dapp.test/2", "999;https://dapp.test/4", "999;https://dapp.test/very_long/url/unusual", "4;5", "999;https://dapp.test/3"]

var search_chan = ["2;id3", "2;id4", "2;id5"]

var search_welcome = ["section2;id2"]

var search_allChats = ["4;12", "4;11", "4;6", "4;101", "4;10", "2;id3", "2;id4", "2;id5", "3;id102", "4;13", "4;2", "3;id106", "4;3", "1;0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8884", "1;0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8882", "1;0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8881", "3;id107", "4;14", "4;7", "4;4", "4;8", "4;18", "4;19", "4;1", "4;17", "4;0", "2;id1", "3;id104", "4;100", "3;id103", "3;id105", "3;id100", "3;id101", "4;9", "1;0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8883", "999;https://dapp.test/2", "999;https://dapp.test/4", "999;https://dapp.test/very_long/url/unusual", "4;5", "999;https://dapp.test/3", "1;0x7F47C2e18a4BBf5487E6fb082eC2D9Ab0E6d7240", "section2;id2"]

var search_nothing = []

var afterInsert = ["1;0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8884", "3;id106", "2;id1", "4;1", "2;new1", "4;12", "4;11", "4;6", "4;101", "4;10", "2;id3", "2;id4", "2;id5", "3;id102", "4;13", "4;2", "4;3", "1;0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8882", "1;0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8881", "3;id107", "4;14", "4;7", "4;4", "4;8", "4;18", "4;19", "4;17", "4;0", "3;id104", "4;100", "3;id103", "3;id105", "3;id100", "3;id101", "4;9", "1;0x7F47C2e98a4BBf5487E6fb082eC2D9Ab0E6d8883", "999;https://dapp.test/2", "999;https://dapp.test/4", "999;https://dapp.test/very_long/url/unusual", "4;5", "999;https://dapp.test/3", "1;0x7F47C2e18a4BBf5487E6fb082eC2D9Ab0E6d7240"]

var visibilityFlags = ["4;12", "4;11", "4;6", "4;101", "4;10", "2;id3", "2;id4", "2;id5", "4;13", "4;2", "4;3", "4;14", "4;7", "4;4", "4;8", "4;18", "4;19", "4;1", "4;17", "4;0", "2;id1", "4;100", "4;9", "4;5"]
