import QtQuick

import utils

ListModel {
    id: root

    function setActiveSection(id: string) {
        const count = root.count
        for (let i = 0; i < count; i++) {
            const section = root.get(i)
            setProperty(i, "active", section.id === id)
        }
    }

    Component.onCompleted: append([
    {
        id: "id0",
        sectionType: Constants.appSection.homePage,
        icon: "home",
        image: "",
        bannerImageData: "",
        color: "mediumblue",
        name: "Home",
        description: "",
        allMembers: [],
        joinedMembersCount: 0,
        activeMembersCount: 0,
        enabled: true,
        hasNotification: false,
        notificationsCount: 0,
        active: false
    },
    {
        id: "id1",
        sectionType: Constants.appSection.chat,
        icon: "chat",
        image: "",
        bannerImageData: "",
        color: "mediumblue",
        name: "Messages",
        description: "",
        allMembers: [],
        joinedMembersCount: 0,
        activeMembersCount: 0,
        enabled: true,
        hasNotification: true,
        notificationsCount: 442,
        active: false
    },
    {
        id: "id2",
        sectionType: Constants.appSection.wallet,
        icon: "wallet",
        image: "",
        bannerImageData: "",
        color: "mediumblue",
        name: "Wallet",
        description: "",
        allMembers: [],
        joinedMembersCount: 0,
        activeMembersCount: 0,
        enabled: true,
        hasNotification: false,
        notificationsCount: 0,
        active: true
    },
    {
        id: "id10",
        sectionType: Constants.appSection.browser,
        icon: "browser",
        image: "",
        bannerImageData: "",
        color: "",
        name: "Browser",
        description: "",
        allMembers: [],
        joinedMembersCount: 0,
        activeMembersCount: 0,
        enabled: true,
        hasNotification: false,
        notificationsCount: 0,
        active: false
    },
    {
        id: "id3",
        sectionType: Constants.appSection.profile,
        icon: "settings",
        image: "",
        bannerImageData: "",
        color: "mediumblue",
        name: "Settings",
        description: "",
        allMembers: [],
        joinedMembersCount: 0,
        activeMembersCount: 0,
        enabled: true,
        hasNotification: true,
        notificationsCount: 0,
        active: false
    },
    {
        id: "id5",
        sectionType: Constants.appSection.communitiesPortal,
        icon: "communities",
        image: "",
        bannerImageData: "",
        color: "mediumblue",
        name: "Communities",
        description: "",
        allMembers: [],
        joinedMembersCount: 0,
        activeMembersCount: 0,
        enabled: true,
        hasNotification: false,
        notificationsCount: 0,
        active: false
    },
    {
        id: "id6",
        sectionType: Constants.appSection.loadingSection,
        icon: "loading",
        image: "",
        bannerImageData: "",
        color: "mediumblue",
        name: "",
        description: "",
        allMembers: [],
        activeMembersCount: 0,
        enabled: true,
        hasNotification: false,
        notificationsCount: 0,
        active: false
    },
    {
        id: "id7",
        sectionType: Constants.appSection.swap,
        icon: "swap",
        image: "",
        bannerImageData: "",
        color: "mediumblue",
        name: "Swap",
        description: "",
        allMembers: [],
        joinedMembersCount: 0,
        activeMembersCount: 0,
        enabled: true,
        hasNotification: false,
        notificationsCount: 0,
        active: false
    },
    {
        id: "id8",
        sectionType: Constants.appSection.market,
        icon: "market",
        image: "",
        bannerImageData: "",
        color: "mediumblue",
        name: "Market",
        description: "",
        allMembers: [],
        joinedMembersCount: 0,
        activeMembersCount: 0,
        enabled: true,
        hasNotification: true,
        notificationsCount: 0,
        active: false
    },
    {
        id: "id9",
        sectionType: Constants.appSection.qrCodeScanner,
        icon: "qr-scan",
        image: "",
        bannerImageData: "",
        color: "",
        name: "QR Scanner",
        description: "QR Code Scanner Popup",
        allMembers: [],
        joinedMembersCount: 0,
        activeMembersCount: 0,
        enabled: true,
        hasNotification: false,
        notificationsCount: 0,
        active: false
    },
    {
        id: "id10",
        sectionType: Constants.appSection.dApp,
        icon: "dApp",
        image: "",
        bannerImageData: "",
        color: "",
        name: "dApp",
        description: "Sample dApp",
        allMembers: [],
        joinedMembersCount: 0,
        activeMembersCount: 0,
        enabled: false,
        hasNotification: false,
        notificationsCount: 0,
        active: false
    },
    {
        id: "id100",
        sectionType: Constants.appSection.community,
        icon: "",
        image: ModelsData.icons.status,
        bannerImageData: ModelsData.banners.status,
        color: "mediumblue",
        name: "Status.app",
        description: "",
        allMembers: [],
        joinedMembersCount: 82,
        activeMembersCount: 61,
        enabled: true,
        hasNotification: true,
        notificationsCount: 3,
        joined: true,
        active: false
    },
    {
        id: "id101",
        sectionType: Constants.appSection.community,
        icon: "",
        image: ModelsData.icons.superRare,
        bannerImageData: ModelsData.banners.superRare,
        color: "slategray",
        name: "SuperRare",
        description: "",
        allMembers: [],
        joinedMembersCount: 10,
        activeMembersCount: 4,
        enabled: true,
        hasNotification: true,
        notificationsCount: 0,
        active: false
    },
    {
        id: "id102",
        sectionType: Constants.appSection.community,
        icon: "",
        image: ModelsData.icons.coinbase,
        bannerImageData: ModelsData.banners.coinbase,
        color: "olive",
        name: "Coinbase",
        description: "",
        allMembers: [],
        joinedMembersCount: 40,
        activeMembersCount: 20,
        enabled: true,
        hasNotification: false,
        notificationsCount: 0,
        spectated: true,
        joined: false,
        active: false
    },
    {
        id: "id103",
        sectionType: Constants.appSection.community,
        icon: "",
        image: ModelsData.icons.socks,
        bannerImageData: ModelsData.banners.socks,
        color: "yellow",
        name: "Socks",
        description: "",
        allMembers: [],
        joinedMembersCount: 42,
        activeMembersCount: 20,
        enabled: true,
        hasNotification: false,
        notificationsCount: 33,
        active: false
    },
    {
        id: "id104",
        sectionType: Constants.appSection.community,
        icon: "",
        image:  ModelsData.icons.rarible,
        bannerImageData: "",
        color: "pink",
        name: "Rarible",
        description: "",
        allMembers: [],
        joinedMembersCount: 1,
        activeMembersCount: 1,
        enabled: true,
        hasNotification: false,
        notificationsCount: 33,
        amIBanned: true,
        active: false
    },
    {
        id: "id105",
        sectionType: Constants.appSection.community,
        icon: "",
        image: ModelsData.icons.spotify,
        bannerImageData: "",
        color: "green",
        name: "Spotify",
        description: "",
        allMembers: ["foo"],
        joinedMembersCount: 10000,
        activeMembersCount: 200,
        enabled: true,
        hasNotification: true,
        notificationsCount: 0,
        active: false
    },
    {
        id: "id106",
        sectionType: Constants.appSection.community,
        icon: "",
        image: ModelsData.icons.dribble,
        bannerImageData: "",
        color: "orange",
        name: "Dribble",
        description: "",
        allMembers: ["foo", "bar", "baz"],
        joinedMembersCount: 3,
        activeMembersCount: 0,
        enabled: true,
        hasNotification: true,
        notificationsCount: 100,
        active: false
    },
    {
        id: "id107",
        sectionType: Constants.appSection.community,
        icon: "",
        image: "",
        bannerImageData: "",
        color: "crimson",
        name: "Just Text",
        description: "",
        allMembers: ["foo"],
        joinedMembersCount: 1,
        activeMembersCount: 0,
        enabled: true,
        hasNotification: false,
        notificationsCount: 0,
        active: false
    },
    ])
}
